In [1]:
import numpy as np
from tensor import Tensor

In [2]:
W = Tensor(np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]))

X = Tensor(np.array([-1, -2, -3]).reshape(-1, 1))

h = W.dot(X)
print(h.value.shape)

W2 = Tensor(np.array([[1, 1, 1]]))

loss = W2.dot(h)
print(loss.value.shape)
print(loss.value)

(3, 1)
(1, 1)
[[-96]]


In [3]:
loss.grad = np.array([[1]])
loss._backward()

In [4]:
W2.grad

array([[-14, -32, -50]])

In [5]:
type(W2)

tensor.Tensor

In [6]:
h.grad

array([[1],
       [1],
       [1]])

In [7]:
h._backward()

In [8]:
W.grad

array([[-1, -2, -3],
       [-1, -2, -3],
       [-1, -2, -3]])

In [9]:
X.grad

array([[12],
       [15],
       [18]])

In [10]:
import torch

In [11]:
Wt = torch.tensor(W.value).float()
Wt.requires_grad = True

In [12]:
Xt = torch.tensor(X.value).float()
Xt.requires_grad = True

In [13]:
h = Wt @ Xt

In [14]:
W2t = torch.tensor([1, 1, 1]).float()
W2t.requires_grad = True

loss = W2t @ h

In [15]:
loss.backward()

In [16]:
W2t.grad.data

tensor([-14., -32., -50.])

In [17]:
loss

tensor([-96.], grad_fn=<SqueezeBackward4>)

In [18]:
Xt.grad.data

tensor([[12.],
        [15.],
        [18.]])

In [19]:
Wt.grad.data

tensor([[-1., -2., -3.],
        [-1., -2., -3.],
        [-1., -2., -3.]])

In [20]:
noop = lambda: None

In [21]:
noop()

In [22]:
np.repeat(np.array([[1, 2, 3]]).reshape(-1, 1), repeats=(5,), axis=1)

array([[1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3]])

In [16]:
from linear import Linear

l1 = Linear(2, 4)

X = Tensor(np.array([
    [0, 0.0],
    [0, 1],
    [1, 0],
    [1, 1]
]))

out = l1.forward(X)

In [17]:
out.value.shape

(4, 4)

In [18]:
l2 = Linear(4, 1)

out2 = l2.forward(out)

In [19]:
out2.value

array([[ 0.        ],
       [-1.58670479],
       [-1.40233376],
       [-2.98903855]])

In [20]:
out3 = out2.sum()

In [21]:
out3.backward()

In [22]:
out3.grad

1

In [23]:
out2.grad

array([[1.],
       [1.],
       [1.],
       [1.]])

In [24]:
l2.W.grad

array([[-2.99423042,  2.40625803, -6.14663346,  4.90443218]])

In [25]:
l2.b.grad

array([[4.]])

In [26]:
l1.W.grad

array([[-1.3266082 , -1.3266082 ],
       [-0.02590484, -0.02590484],
       [ 2.51080649,  2.51080649],
       [-0.08828421, -0.08828421]])

In [27]:
l1.b.grad

array([[-2.6532164 , -0.05180968,  5.02161297, -0.17656841]])

In [31]:
import torch.nn as nn

Xt = torch.tensor([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
]).float()

W1t = torch.tensor(l1.W.value).float()
W1t.requires_grad = True


b1t = torch.tensor(l1.b.value).float()
b1t.requires_grad = True

W2t = torch.tensor(l2.W.value).float()
W2t.requires_grad = True

b2t = torch.tensor(l2.b.value).float()
b2t.requires_grad = True

ht = Xt @ W1t.T + b1t
h2t = ht @ W2t.T + b2t
h3t = h2t.sum()

In [32]:
h3t.backward()

In [35]:
W1t.grad.data

tensor([[-1.3266, -1.3266],
        [-0.0259, -0.0259],
        [ 2.5108,  2.5108],
        [-0.0883, -0.0883]])

In [36]:
b1t.grad.data

tensor([[-2.6532, -0.0518,  5.0216, -0.1766]])