In [1]:
from tensor import Tensor
from linear import Linear
from cross_entropy_loss import CELossWithLogits
import numpy as np
import torch

In [2]:
l1 = Linear(2, 4)
l2 = Linear(4, 2)

X = Tensor(np.array([
    [0, 0.0],
    [0, 1],
    [1, 0],
    [1, 1]
]))

# left = 0, right = 1 
y_true = Tensor(np.array([
    [1, 0],
    [0, 1],
    [0, 1],
    [1, 0]
]))

h1 = l1.forward(X)
logits = l2.forward(h1)

criterion = CELossWithLogits()

loss = criterion.forward(logits, y_true)

In [3]:
print(logits.value)

[[ 0.          0.        ]
 [-2.28363504 -0.17628375]
 [ 0.06583001  0.92282901]
 [-2.21780502  0.74654527]]


In [4]:
loss.value

np.float64(1.0440747931243872)

In [5]:
loss.backward()

In [6]:
l1.W.grad

array([[ 0.11604089,  0.149732  ],
       [ 0.15938835,  0.20566489],
       [ 0.10929151,  0.14102301],
       [-0.24038182, -0.31017386]])

In [7]:
l1.b.grad

array([[ 0.18563579,  0.25498066,  0.1748385 , -0.38454953]])

In [8]:
# check with torch
Xt = torch.tensor([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
]).float()

yt = torch.tensor([0, 1, 1, 0])

W1t = torch.tensor(l1.W.value).float()
W1t.requires_grad = True


b1t = torch.tensor(l1.b.value).float()
b1t.requires_grad = True

W2t = torch.tensor(l2.W.value).float()
W2t.requires_grad = True

b2t = torch.tensor(l2.b.value).float()
b2t.requires_grad = True

ht = Xt @ W1t.T + b1t
logits_t = ht @ W2t.T + b2t
print(logits_t)

criterion_torch = torch.nn.CrossEntropyLoss()

loss_t = criterion_torch(logits_t, yt)

tensor([[ 0.0000,  0.0000],
        [-2.2836, -0.1763],
        [ 0.0658,  0.9228],
        [-2.2178,  0.7465]], grad_fn=<AddBackward0>)


In [9]:
loss_t

tensor(1.0441, grad_fn=<NllLossBackward0>)

In [12]:
loss_t.backward()

In [13]:
W1t.grad.data

tensor([[ 0.1160,  0.1497],
        [ 0.1594,  0.2057],
        [ 0.1093,  0.1410],
        [-0.2404, -0.3102]])