In [1]:
from tensor import Tensor
from linear import Linear
from cross_entropy_loss import CELossWithLogits
import numpy as np
import torch
from layer import Layer
from sequential import Sequential
from relu import ReLU

In [2]:
X = Tensor(np.array([
    [0, 0.0],
    [0, 1],
    [1, 0],
    [1, 1]
]))

# left = 0, right = 1 
y_true = Tensor(np.array([
    [1, 0],
    [0, 1],
    [0, 1],
    [1, 0]
]))

nn = Sequential(
    Linear(2, 4),
    ReLU(),
    Linear(4, 2)
)

logits = nn.forward(X)

criterion = CELossWithLogits()

loss = criterion.forward(logits, y_true)

In [3]:
nn.get_params()

{'Linear0W': <tensor.Tensor at 0x7801ec40f7f0>,
 'Linear0b': <tensor.Tensor at 0x7801ec40f640>,
 'Linear2W': <tensor.Tensor at 0x78010a27eb00>,
 'Linear2b': <tensor.Tensor at 0x78010a2ae0b0>}

In [4]:
print(nn.layers[0])

Linear


In [5]:
print(logits.value)

[[ 0.          0.        ]
 [ 0.26221638  0.04884685]
 [ 0.08968821 -0.02690637]
 [ 0.10496067 -0.0314881 ]]


In [6]:
loss.value

np.float64(0.7197625637831777)

In [4]:
loss.backward()

In [5]:
nn.get_params()["Linear0W"].grad

array([[ 0.        ,  0.        ],
       [ 0.        ,  0.        ],
       [ 0.16856773, -0.03099488],
       [-0.01747358,  0.06906943]])

In [6]:
nn.get_params()["Linear0b"].grad

array([[0.        , 0.        , 0.16856773, 0.06906943]])

In [8]:
# check with torch
Xt = torch.tensor([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
]).float()

yt = torch.tensor([0, 1, 1, 0])

p = nn.get_params()

W1t = torch.tensor(p["Linear0W"].value).float()
W1t.requires_grad = True


b1t = torch.tensor(p["Linear0W"].b.value).float()
b1t.requires_grad = True

W2t = torch.tensor(p["Linear1W"].W.value).float()
W2t.requires_grad = True

b2t = torch.tensor(p["Linear1b"].b.value).float()
b2t.requires_grad = True

ht = torch.nn.functional.relu(Xt @ W1t.T + b1t)
logits_t = ht @ W2t.T + b2t

criterion_torch = torch.nn.CrossEntropyLoss()

loss_t = criterion_torch(logits_t, yt)

tensor([[ 0.0000,  0.0000],
        [-2.2836, -0.1763],
        [ 0.0658,  0.9228],
        [-2.2178,  0.7465]], grad_fn=<AddBackward0>)


In [9]:
loss_t

tensor(1.0441, grad_fn=<NllLossBackward0>)

In [12]:
loss_t.backward()

In [13]:
W1t.grad.data

tensor([[ 0.1160,  0.1497],
        [ 0.1594,  0.2057],
        [ 0.1093,  0.1410],
        [-0.2404, -0.3102]])

In [14]:
def moin(*args):

    for arg in args:
        print(arg)

In [15]:
moin("Hallo", "Wie ", "Gehts", "Heute")

Hallo
Wie 
Gehts
Heute
